main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: rfresh2
description: Paper packet logger
commands:
  pls:
    description: Start packetlogging
    usage: "pls"
    aliases: packetlogstart
  ple:
    description: End packetlogging
    usage: "ple"
    aliases: packetlogend
depend:
  - packetevents
